### PR TITLE
Added CLI

### PR DESCRIPTION
**Pull request by dhruvpeter**
Program can now be run using `python main.py config.yaml`
config.yaml is provided as command line input
To see usage and description, type `python main.py -h` in terminal
#8

### CODE REVIEW

**Comment by dhruvpeter** [comment]
Update README.md using CLI syntax

**Comment by abose** [comment]
@dhruvpeter Thanks for contributing. 
Can you also post a sample CLI input and output?

**Comment by dhruvpeter** [comment]
Input: python main.py -h

Output:
usage: python main.py <file> 

Description:
App info extractor is a utility to extract and analyze customer reviews and critical metrics of apps from multiple   
sources like google play store, Apple play store, and anyother sources.This utility is highly configurable to extract
and give relevant information about any app in a meaningful way.

positional arguments:
  file        config.yaml file containing the configuration for each app

optional arguments:
  -h, --help  show this help message and exit

**Comment by abose** [comment]
Thanks for contributing to open source @ core.ai @dhruvpeter 
The changes are merged.

**Pull request merged**
